
name: build-image

on:
  push:
    branches: ['main', 'ci_action']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          architecture: x64
      
      - name: Bump version and push tag
        uses: hennejg/github-tag-action@v4.1.jh1
        id: tag
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag.outputs.new_tag }}
          generateReleaseNotes: true
          bodyFile: "body.md"
      
      - name: Publish container image
        run: |
          ./mvnw install \
            -Dmaven.test.skip \
            -Dquarkus.profile=deliver \
            -Dquarkus.container-image.tag=${{ steps.tag.outputs.new_tag }}
